name: sigb-dev

volumes:
  data:

services:
  db:
    image: postgres:16-alpine
    restart: always
    user: postgres
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES__PASSWD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 20s
      retries: 3
      start_period: 10s

  web:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    environment:
      DJANGO__SECRET_KEY: ${DJANGO__SECRET_KEY}
      DJANGO__DEBUG: ${DJANGO__DEBUG:-1}
      DJANGO__ALLOWED_HOSTS: ${DJANGO__ALLOWED_HOSTS:-*}
      DJANGO__CSRF_TRUSTED_ORIGINS: ${DJANGO__CSRF_TRUSTED_ORIGINS:-http://*}
      POSTGRES__PASSWD: ${POSTGRES__PASSWD}
    ports:
      - 8000:8000
    volumes:
      - ./sigb:/app/sigb
      - ./sigb/logs:/app/sigb/logs
    depends_on:
      db:
        condition: service_healthy
