# Generated by Django 5.1.5 on 2025-02-17 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade', models.CharField(max_length=255)),
                ('carga_horaria', models.IntegerField()),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Bolsista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('dt_nascimento', models.DateField()),
                ('nome_mae', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('pis_pasep', models.CharField()),
                ('conta_bancaria', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=8)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.IntegerField()),
                ('cidade', models.CharField(max_length=255)),
                ('uf', models.CharField(max_length=2)),
                ('documentacao', models.FileField(upload_to='bolsista_documentacao')),
            ],
        ),
        migrations.CreateModel(
            name='Edital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('vigencia', models.DateField()),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RelacaoBolistaBolsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(max_length=255)),
                ('situacao', models.CharField(max_length=255)),
                ('dt_desligamento', models.DateField()),
                ('vigencia_outorga', models.DateField()),
                ('data_outorga', models.DateField()),
                ('termo_outorga', models.FileField(blank=True, null=True, upload_to='termo_outorga')),
                ('bolsa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.bolsa')),
                ('bolsista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bolsista')),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.edital')),
            ],
        ),
    ]
