# Generated by Django 5.1.5 on 2025-02-06 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolsista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('dt_nascimento', models.DateField()),
                ('nome_mae', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('pis_pasep', models.CharField()),
                ('dados_bancários', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=8)),
                ('endereco', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Bolsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('modalidade', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('carga_horaria', models.IntegerField()),
                ('valor', models.FloatField()),
                ('bolsista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bolsista')),
            ],
        ),
        migrations.CreateModel(
            name='Edital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('identificador', models.CharField(max_length=255)),
                ('dt_assinatura', models.DateField()),
                ('data_final', models.DateField()),
                ('bolsistas', models.ManyToManyField(to='core.bolsista')),
            ],
        ),
    ]
