# Generated by Django 5.1.5 on 2025-02-20 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BolsistaBolsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(max_length=255)),
                ('situacao', models.CharField(max_length=255)),
                ('dt_desligamento', models.DateField()),
                ('vigencia_outorga', models.DateField()),
                ('data_outorga', models.DateField()),
                ('termo_outorga', models.FileField(blank=True, null=True, upload_to='termo_outorga')),
                ('bolsa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.bolsa')),
                ('bolsista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bolsista')),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.edital')),
            ],
        ),
        migrations.DeleteModel(
            name='RelacaoBolistaBolsa',
        ),
    ]
