# Generated by Django 5.1.5 on 2025-02-08 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bolsista',
            old_name='dados_bancários',
            new_name='dados_bancarios',
        ),
    ]
