# Generated by Django 5.1.5 on 2025-02-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_bolsistabolsa_dt_desligamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolsista',
            name='documentacao',
            field=models.FileField(blank=True, null=True, upload_to='bolsista_documentacao'),
        ),
    ]
